import json

res = json.loads('{"tracks": {"href": "https://api.spotify.com/v1/search?query=Leave+The+Door+Open&type=track&offset=0&limit=1", "items": [{"album": {"album_type": "single", "artists": [{"external_urls": {"spotify": "https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C"}, "href": "https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C", "id": "0du5cEVh5yTK9QJze8zA0C", "name": "Bruno Mars", "type": "artist", "uri": "spotify:artist:0du5cEVh5yTK9QJze8zA0C"}, {"external_urls": {"spotify": "https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"}, "href": "https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa", "id": "3jK9MiCrA42lLAdMGUZpwa", "name": "Anderson .Paak", "type": "artist", "uri": "spotify:artist:3jK9MiCrA42lLAdMGUZpwa"}, {"external_urls": {"spotify": "https://open.spotify.com/artist/6PvvGcCY2XtUcSRld1Wilr"}, "href": "https://api.spotify.com/v1/artists/6PvvGcCY2XtUcSRld1Wilr", "id": "6PvvGcCY2XtUcSRld1Wilr", \
"name": "Silk Sonic", "type": "artist", "uri": "spotify:artist:6PvvGcCY2XtUcSRld1Wilr"}], "available_markets": ["AD", "AE", "AG", "AL", "AM", "AO", "AR", "AT", "AU", "AZ", "BA", "BB", \
"BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CH", "CI", "CL", "CM", "CO", "CR", "CV", "CW", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "FI", "FJ", "FM", "FR", "GA", "GB", "GD", "GE", "GH", "GM", \
"GN", "GQ", "GR", "GT", "GW", "GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IS", "IT", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KR", "KW", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "MA", "MC", "MD", "ME", "MG", "MH", "MK", \
"ML", "MN", "MO", "MR", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SE", "SG", "SI", "SK", "SL", "SM", "SN", \
"SR", "ST", "SV", "SZ", "TD", "TG", "TH", "TL", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "UY", "UZ", "VC", "VN", "VU", "WS", "XK", "ZA", "ZM", "ZW"], "external_urls": {"spotify": "https://open.spotify.com/album/7dfPqXck6BB9wpThrVYBss"}, "href": "https://api.spotify.com/v1/albums/7dfPqXck6BB9wpThrVYBss", "id": "7dfPqXck6BB9wpThrVYBss", "images": [{"height": 640, "url": "https://i.scdn.co/image/ab67616d0000b2736f9e6abbd6fa43ac3cdbeee0", "width": 640}, {"height": 300, "url": "https://i.scdn.co/image/ab67616d00001e026f9e6abbd6fa43ac3cdbeee0", "width": 300}, {"height": 64, "url": "https://i.scdn.co/image/ab67616d000048516f9e6abbd6fa43ac3cdbeee0", "width": 64}], "name": "Leave The Door Open", "release_date": "2021-03-05", "release_date_precision": "day", "total_tracks": 1, "type": "album", "uri": "spotify:album:7dfPqXck6BB9wpThrVYBss"}, "artists": [{"external_urls": {"spotify": "https://open.spotify.com/artist/0du5cEVh5yTK9QJze8zA0C"}, "href": "https://api.spotify.com/v1/artists/0du5cEVh5yTK9QJze8zA0C", "id": "0du5cEVh5yTK9QJze8zA0C", "name": "Bruno Mars", "type": "artist", \
"uri": "spotify:artist:0du5cEVh5yTK9QJze8zA0C"}, {"external_urls": {"spotify": "https://open.spotify.com/artist/3jK9MiCrA42lLAdMGUZpwa"}, "href": "https://api.spotify.com/v1/artists/3jK9MiCrA42lLAdMGUZpwa", "id": "3jK9MiCrA42lLAdMGUZpwa", "name": "Anderson .Paak", "type": "artist", "uri": "spotify:artist:3jK9MiCrA42lLAdMGUZpwa"}, {"external_urls": {"spotify": "https://open.spotify.com/artist/6PvvGcCY2XtUcSRld1Wilr"}, "href": "https://api.spotify.com/v1/artists/6PvvGcCY2XtUcSRld1Wilr", "id": "6PvvGcCY2XtUcSRld1Wilr", "name": "Silk Sonic", "type": \
"artist", "uri": "spotify:artist:6PvvGcCY2XtUcSRld1Wilr"}], "available_markets": ["AD", "AE", "AG", "AL", "AM", "AO", "AR", "AT", "AU", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", \
"BI", "BJ", "BN", "BO", "BR", "BS", "BT", "BW", "BY", "BZ", "CA", "CH", "CI", "CL", "CM", "CO", "CR", "CV", "CW", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE", "EG", "ES", "FI", "FJ", "FM", "FR", "GA", "GB", "GD", "GE", "GH", "GM", "GN", "GQ", "GR", "GT", "GW", \
"GY", "HK", "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IN", "IS", "IT", "JM", "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KR", "KW", "KZ", "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "MA", "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MN", "MO", "MR", "MT", \
"MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NE", "NG", "NI", "NL", "NO", "NP", "NR", "NZ", "OM", "PA", "PE", "PG", "PH", "PK", "PL", "PS", "PT", "PW", "PY", "QA", "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SE", "SG", "SI", "SK", "SL", "SM", "SN", "SR", "ST", "SV", "SZ", "TD", \
"TG", "TH", "TL", "TN", "TO", "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "US", "UY", "UZ", "VC", "VN", "VU", "WS", "XK", "ZA", "ZM", "ZW"], "disc_number": 1, "duration_ms": 242096, "explicit": False, "external_ids": {"isrc": "USAT22100906"}, "external_urls": {"spotify": "https://open.spotify.com/track/7MAibcTli4IisCtbHKrGMh"}, "href": "https://api.spotify.com/v1/tracks/7MAibcTli4IisCtbHKrGMh", "id": "7MAibcTli4IisCtbHKrGMh", "is_local": False, "name": "Leave The Door Open", "popularity": 96, "preview_url": "https://p.scdn.co/mp3-preview/98f4a6a2e2c031e272ffc93c5fec5d7cb43de490?cid=6e87b90752bd446c9975bed426f6e946", "track_number": 1, "type": "track", "uri": "spotify:track:7MAibcTli4IisCtbHKrGMh"}], "limit": 1, "next": "https://api.spotify.com/v1/search?query=Leave+The+Door+Open&type=track&offset=1&limit=1", "offset": \
0, "previous": None, "total": 523}}')

print(res)
